version: '3.8'

services:
  redisprimarycache:
    image: redis:latest
    container_name: redisprimarycache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redissecondarycache:
    image: redis:latest
    container_name: redissecondarycache
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data

volumes:
  redis_data:
  mongo_data: